server {
    listen 3000;
    server_name _;
    root /var/www;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1000;

    expires 1d;
    add_header Cache-Control "public, no-transform";
}